### ISSUE TITLE
Depend on `dicom` instead of `pydicom`

### ISSUE THREAD

**Issue by jreut** [chop-dbhi/dicom-anon#22]
Thanks for providing this useful program! I ran into a small problem while setting it up, and I wanted to bring it to your attention. It seems like the `pydicom` project has changed the way it is intended to be imported.

```sh
git clone https://github.com/chop-dbhi/dicom-anon.git
cd dicom-anon.git
pip2 install -r requirements.txt
#=> Successfully installed pydicom-1.0.2
```

Running `python2 dicom_anon.py` gives this error message:

```
Traceback (most recent call last):
  File "dicom_anon.py", line 23, in <module>
    import dicom
  File "/usr/local/lib/python2.7/site-packages/dicom.py", line 11, in <module>
    raise ImportError(msg)
ImportError: 
Pydicom via 'import dicom' has been removed in pydicom version 1.0.
Please install the `dicom` package to restore function of code relying
on pydicom 0.9.9 or earlier. E.g. `pip install dicom`.
Alternatively, most code can easily be converted to pydicom > 1.0 by
changing import lines from 'import dicom' to 'import pydicom'.
See the Transition Guide at
https://pydicom.github.io/pydicom/stable/transition_to_pydicom1.html.
```

From reading the [pydicom documentation](https://pydicom.github.io/pydicom/stable/transition_to_pydicom1.html#for-authors-of-packages-requiring-pydicom-1-0), I think this can be fixed by depending on the `dicom` library instead of the `pydicom` library.

A patch like this seems to work:

```diff
diff --git a/requirements.txt b/requirements.txt
index a681f02..8314cfa 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -4,4 +4,4 @@
 #
 #     pip install -U -r requirements.txt
 
-pydicom
+dicom==0.9.9.post1
```

I'm happy to submit a pull request with this patch. Thanks again!

**Comment by jeffmax** [comment]
@jreut Thanks for pointing this out! If you can submit a pull request that would be very helpful.
